name = "CC Factions"
author = "piguman3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba0f233fd1126c4dd839c126107e5c7c9ea75ea7ab1e0881f24ea3e34e027578"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
