name = "CC Factions"
author = "piguman3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25bb3d5673c0341ebed17da6cdc4b6550cff6e418b2e5b652657090a6d9ee984"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
